language: php
dist: bionic

php:
  - 7.1
  - 7.2
  - 7.3

install:
    - composer install --prefer-source

script:
    - vendor/bin/peridot specs/
    - vendor/bin/peridot app/specs/

matrix:
  fast_finish: true
